Repository appleseedhq/appleseed, pull requests merged in 2018-10, with the labels that each got.

#2237 Fix sample count aov and add feedback on noise level in the adaptive …
  src/appleseed/foundation/image/filteredtile.cpp
  src/appleseed/foundation/image/filteredtile.h
  src/appleseed/renderer/kernel/rendering/final/adaptivetilerenderer.cpp
  src/appleseed/renderer/modeling/aov/diagnosticaov.cpp
Labels: PR-Squash

#2248 Fix typo
  src/appleseed.shaders/src/appleseed/as_globals.osl
Labels: Documentation

#2244 Normalize Pixel Sample Count AOV depending on sampling settings
  src/appleseed/renderer/kernel/rendering/final/adaptivepixelrenderer.cpp
  src/appleseed/renderer/kernel/rendering/final/adaptivetilerenderer.cpp
  src/appleseed/renderer/kernel/rendering/final/uniformpixelrenderer.cpp
  src/appleseed/renderer/modeling/aov/diagnosticaov.cpp
  src/appleseed/renderer/modeling/aov/diagnosticaov.h
Labels: PR-Squash

#2257 Stratifies samples in BSSRDF unit tests
  src/appleseed/renderer/meta/tests/test_sss.cpp
Labels: PR-Rebase
