Repository appleseedhq/appleseed, pull requests merged in 2018-11, with the labels that each got.

#2196 Do not store zero weight in `Foundation::cdf`
  src/appleseed/foundation/math/cdf.h
Labels: PR-Squash

#2271 Linux clang support
  CMakeLists.txt
  cmake/config/linux-gcc-clang.txt
  src/appleseed.studio/mainwindow/project/disneymateriallayerui.cpp
  src/appleseed.studio/mainwindow/project/entitybrowser.h
  src/appleseed.studio/mainwindow/project/entityeditor.cpp
  src/appleseed/foundation/meta/tests/test_imageimportancesampler.cpp
  src/appleseed/foundation/meta/tests/test_matrix.cpp
  src/appleseed/foundation/meta/tests/test_microfacet.cpp
  src/appleseed/foundation/utility/api/apiarray.h
  src/appleseed/renderer/kernel/aov/aovaccumulator.cpp
  src/appleseed/renderer/kernel/lighting/backwardlightsampler.h
  src/appleseed/renderer/kernel/lighting/lighttracing/lighttracingsamplegenerator.cpp
  src/appleseed/renderer/kernel/lighting/sppm/sppmphotontracer.cpp
  src/appleseed/renderer/kernel/lighting/tracer.cpp
  src/appleseed/renderer/kernel/lighting/tracer.h
  src/appleseed/renderer/kernel/lighting/volumelightingintegrator.cpp
  src/appleseed/renderer/kernel/rendering/generic/genericsamplegenerator.cpp
  src/appleseed/renderer/kernel/rendering/generic/genericsamplerenderer.cpp
  src/appleseed/renderer/kernel/rendering/progressive/progressiveframerenderer.cpp
  src/appleseed/renderer/kernel/rendering/progressive/samplegeneratorjob.cpp
  src/appleseed/renderer/kernel/rendering/progressive/samplegeneratorjob.h
  src/appleseed/renderer/kernel/shading/shadingcontext.cpp
  src/appleseed/renderer/meta/tests/test_dynamicspectrum.cpp
  src/appleseed/renderer/meta/tests/test_environmentedf.cpp
  src/appleseed/renderer/meta/tests/test_imagetools.cpp
  src/appleseed/renderer/meta/tests/test_tracer.cpp
  src/appleseed/renderer/meta/tests/test_volume.cpp
  src/appleseed/renderer/modeling/aov/diagnosticaov.cpp
  src/appleseed/renderer/modeling/postprocessingstage/colormappostprocessingstage.cpp
  src/appleseed/renderer/modeling/project/projectfilereader.cpp
  src/appleseed/renderer/modeling/surfaceshader/aosurfaceshader.cpp
  src/thirdparty/bcd/bcd/MultiscaleDenoiser.cpp
Labels: PR-Rebase

#2285 Making Cornell Box's Background Solid Black
  src/appleseed/renderer/modeling/project-builtin/cornellboxproject.cpp
Labels: PR-Squash

#2268 Hide node input in node editor (maya, blender, gaffer)
  src/appleseed.shaders/src/appleseed/as_blackbody.osl
  src/appleseed.shaders/src/appleseed/as_fresnel.osl
  src/appleseed.shaders/src/appleseed/as_metal.osl
  src/appleseed.shaders/src/appleseed/as_sbs_pbrmaterial.osl
  src/appleseed.shaders/src/appleseed/as_standard_surface.osl
  src/appleseed.shaders/src/appleseed/as_toon.osl
  src/appleseed.shaders/src/maya/as_maya_anisotropic.osl
  src/appleseed.shaders/src/maya/as_maya_blinn.osl
  src/appleseed.shaders/src/maya/as_maya_cloud.osl
  src/appleseed.shaders/src/maya/as_maya_lambert.osl
  src/appleseed.shaders/src/maya/as_maya_phong.osl
  src/appleseed.shaders/src/maya/as_maya_phongE.osl
  src/appleseed.shaders/src/maya/as_maya_samplerInfo.osl
Labels: OSL, appleseed.shaders

#2288 Add max ray intensity for SPPM
  sandbox/tests/test scenes/max ray intensity/01 - pt.appleseed
  sandbox/tests/test scenes/max ray intensity/02 - sppm.appleseed
  sandbox/tests/test scenes/max ray intensity/ref/01 - pt.png
  sandbox/tests/test scenes/max ray intensity/ref/02 - sppm.png
  src/appleseed.studio/mainwindow/renderingsettingswindow.cpp
  src/appleseed/CMakeLists.txt
  src/appleseed/renderer/kernel/lighting/pt/ptlightingengine.cpp
  src/appleseed/renderer/kernel/lighting/sppm/sppmlightingengine.cpp
  src/appleseed/renderer/kernel/lighting/sppm/sppmparameters.cpp
  src/appleseed/renderer/kernel/lighting/sppm/sppmparameters.h
  src/appleseed/renderer/utility/spectrumclamp.h
Labels: PR-Rebase

#2258 Remove mesh regions
  sandbox/samples/cpp/distancefieldobject/distancefieldobject.cpp
  sandbox/samples/cpp/infiniteplaneobject/infiniteplaneobject.cpp
  sandbox/samples/cpp/sphereobject/sphereobject.cpp
  sandbox/tests/unit tests/inputs/test_projectfilereader_configurationblocks.appleseed
  src/appleseed/CMakeLists.txt
  src/appleseed/renderer/kernel/intersection/assemblytree.cpp
  src/appleseed/renderer/kernel/intersection/assemblytree.h
  src/appleseed/renderer/kernel/intersection/curvetree.cpp
  src/appleseed/renderer/kernel/intersection/embreescene.cpp
  src/appleseed/renderer/kernel/intersection/intersectionfilter.cpp
  src/appleseed/renderer/kernel/intersection/intersectionfilter.h
  src/appleseed/renderer/kernel/intersection/intersectionsettings.h
  src/appleseed/renderer/kernel/intersection/intersector.cpp
  src/appleseed/renderer/kernel/intersection/intersector.h
  src/appleseed/renderer/kernel/intersection/regioninfo.h
  src/appleseed/renderer/kernel/intersection/regiontree.cpp
  src/appleseed/renderer/kernel/intersection/regiontree.h
  src/appleseed/renderer/kernel/intersection/tracecontext.cpp
  src/appleseed/renderer/kernel/intersection/trianglekey.h
  src/appleseed/renderer/kernel/intersection/triangletree.cpp
  src/appleseed/renderer/kernel/intersection/triangletree.h
  src/appleseed/renderer/kernel/lighting/backwardlightsampler.cpp
  src/appleseed/renderer/kernel/lighting/forwardlightsampler.cpp
  src/appleseed/renderer/kernel/lighting/lightsample.cpp
  src/appleseed/renderer/kernel/lighting/lightsample.h
  src/appleseed/renderer/kernel/lighting/lightsamplerbase.cpp
  src/appleseed/renderer/kernel/lighting/lighttypes.h
  src/appleseed/renderer/kernel/shading/fastambientocclusion.cpp
  src/appleseed/renderer/kernel/shading/shadingpoint.cpp
  src/appleseed/renderer/kernel/shading/shadingpoint.h
  src/appleseed/renderer/modeling/object/curveobject.cpp
  src/appleseed/renderer/modeling/object/curveobject.h
  src/appleseed/renderer/modeling/object/iregion.h
  src/appleseed/renderer/modeling/object/meshobject.cpp
  src/appleseed/renderer/modeling/object/meshobject.h
  src/appleseed/renderer/modeling/object/object.h
  src/appleseed/renderer/modeling/object/regionkit.h
  src/appleseed/renderer/modeling/project/projectfileupdater.cpp
  src/appleseed/renderer/modeling/project/projectformatrevision.h
  src/appleseed/renderer/modeling/scene/assembly.cpp
  src/appleseed/renderer/modeling/scene/assembly.h
  src/appleseed/renderer/modeling/surfaceshader/diagnosticsurfaceshader.cpp
  src/appleseed/renderer/modeling/surfaceshader/diagnosticsurfaceshader.h
  src/appleseed/renderer/utility/testutils.cpp
  src/appleseed/renderer/utility/testutils.h
Labels: PR-Squash

#2300 Fix time on render stamp when pausing rendering
  src/appleseed/renderer/kernel/rendering/masterrenderer.cpp
Labels: PR-Rebase

#2302 Refactor AOV and tile bbox code
  src/appleseed/CMakeLists.txt
  src/appleseed/renderer/api/aov.h
  src/appleseed/renderer/kernel/aov/aovaccumulator.cpp
  src/appleseed/renderer/kernel/aov/aovaccumulator.h
  src/appleseed/renderer/kernel/rendering/final/adaptivepixelrenderer.cpp
  src/appleseed/renderer/kernel/rendering/final/adaptivetilerenderer.cpp
  src/appleseed/renderer/kernel/rendering/final/uniformpixelrenderer.cpp
  src/appleseed/renderer/kernel/rendering/generic/generictilerenderer.cpp
  src/appleseed/renderer/modeling/aov/albedoaov.cpp
  src/appleseed/renderer/modeling/aov/aov.cpp
  src/appleseed/renderer/modeling/aov/aov.h
  src/appleseed/renderer/modeling/aov/aovfactoryregistrar.cpp
  src/appleseed/renderer/modeling/aov/denoiseraov.cpp
  src/appleseed/renderer/modeling/aov/denoiseraov.h
  src/appleseed/renderer/modeling/aov/depthaov.cpp
  src/appleseed/renderer/modeling/aov/diagnosticaov.cpp
  src/appleseed/renderer/modeling/aov/diffuseaov.cpp
  src/appleseed/renderer/modeling/aov/emissionaov.cpp
  src/appleseed/renderer/modeling/aov/glossyaov.cpp
  src/appleseed/renderer/modeling/aov/invalidsamplesaov.cpp
  src/appleseed/renderer/modeling/aov/invalidsamplesaov.h
  src/appleseed/renderer/modeling/aov/normalaov.cpp
  src/appleseed/renderer/modeling/aov/npraovs.cpp
  src/appleseed/renderer/modeling/aov/pixelsamplecountaov.cpp
  src/appleseed/renderer/modeling/aov/pixelsamplecountaov.h
  src/appleseed/renderer/modeling/aov/pixeltimeaov.cpp
  src/appleseed/renderer/modeling/aov/pixelvariationaov.cpp
  src/appleseed/renderer/modeling/aov/pixelvariationaov.h
  src/appleseed/renderer/modeling/aov/positionaov.cpp
  src/appleseed/renderer/modeling/aov/uvaov.cpp
  src/appleseed/renderer/modeling/frame/frame.cpp
  src/appleseed/renderer/utility/bbox.h
Labels: PR-Squash

#2309 Expose library info and third party version info to Python bindings
  src/appleseed.python/CMakeLists.txt
  src/appleseed.python/bindappleseed.cpp
  src/appleseed.python/module.cpp
  src/appleseed.studio/CMakeLists.txt
Labels: PR-Squash

#2301 Add triangulation stage to C++ blenderseed exporter
  src/appleseed.python/CMakeLists.txt
  src/appleseed.python/bindblendermeshconverter.cpp
Labels: PR-Squash
