Repository appleseedhq/appleseed, pull requests merged in 2018-08, with the labels that each got.

#2149 Added emission NPR getter
  src/appleseed/renderer/kernel/rendering/rendererservices.cpp
  src/appleseed/renderer/kernel/rendering/rendererservices.h
  src/appleseed/renderer/kernel/shading/shadingpoint.h
  src/appleseed/renderer/modeling/surfaceshader/nprsurfaceshaderhelper.cpp
Labels: Feature, OSL

#2158 Fix Fresnel
  src/appleseed.shaders/src/appleseed/as_toon.osl
Labels: Bug

#2166 [WIP] debugging travis (macOS build bot)
  travis/build-macos.sh
Labels: PR-Squash

#2172 Add manifold2d node
  src/appleseed.shaders/CMakeLists.txt
  src/appleseed.shaders/src/appleseed/as_attributes.osl
  src/appleseed.shaders/src/appleseed/as_globals.osl
  src/appleseed.shaders/src/appleseed/as_manifold2d.osl
  src/appleseed/renderer/modeling/shadergroup/shaderquery.cpp
Labels: Feature, OSL, appleseed.shaders
