Repository appleseedhq/appleseed, pull requests merged in 2019-03, with the labels that each got.

#2352 Add support of Cryptomatte AOV
  CMakeLists.txt
  src/appleseed/CMakeLists.txt
  src/appleseed/renderer/modeling/aov/aovfactoryregistrar.cpp
  src/appleseed/renderer/modeling/aov/cryptomatteaov.cpp
  src/appleseed/renderer/modeling/aov/cryptomatteaov.h
  src/thirdparty/murmurhash3/CMakeLists.txt
  src/thirdparty/murmurhash3/MurmurHash3.cpp
  src/thirdparty/murmurhash3/MurmurHash3.h
Labels: Feature, PR-Squash

#2445 Support write all formats images using OIIO
  src/appleseed.studio/mainwindow/mainwindow.cpp
  src/appleseed/foundation/image/genericimagefilewriter.cpp
  src/appleseed/foundation/image/image.cpp
  src/appleseed/foundation/image/image.h
  src/appleseed/renderer/modeling/frame/frame.cpp
Labels: WIP

#2468 Implement render stamp scaling
  src/appleseed/CMakeLists.txt
  src/appleseed/foundation/resources/logo/appleseed-seeds-256.cpp
  src/appleseed/foundation/resources/logo/appleseed-seeds-256.h
  src/appleseed/renderer/modeling/postprocessingstage/renderstamppostprocessingstage.cpp
Labels: PR-Squash

#2432 Implementing drag & drop to apply materials
  src/appleseed.studio/CMakeLists.txt
  src/appleseed.studio/mainwindow/mainwindow.cpp
  src/appleseed.studio/mainwindow/project/itembase.cpp
  src/appleseed.studio/mainwindow/project/materialassignmenteditorwindow.cpp
  src/appleseed.studio/mainwindow/project/materialitem.cpp
  src/appleseed.studio/mainwindow/project/projectexplorer.cpp
  src/appleseed.studio/mainwindow/project/projectexplorer.h
  src/appleseed.studio/mainwindow/rendering/materialdrophandler.cpp
  src/appleseed.studio/mainwindow/rendering/materialdrophandler.h
  src/appleseed.studio/mainwindow/rendering/rendertab.cpp
  src/appleseed.studio/mainwindow/rendering/rendertab.h
  src/appleseed.studio/mainwindow/rendering/renderwidget.cpp
  src/appleseed.studio/mainwindow/rendering/renderwidget.h
  src/appleseed/renderer/kernel/rendering/scenepicker.h
  src/appleseed/renderer/kernel/shading/shadingpoint.h
Labels: PR-Squash
