Repository appleseedhq/appleseed, pull requests merged in 2019-05, with the labels that each got.

#2570 Increase precision of floating point values in text files
  src/appleseed/foundation/mesh/objmeshfilewriter.cpp
  src/appleseed/foundation/meta/tests/test_qmc.cpp
  src/appleseed/foundation/resources/logo/generatelogofiles.cpp
  src/appleseed/renderer/modeling/project/projectfilewriter.cpp
Labels: PR-Squash

#2583 Add uniform sampling on analytic spheres and disks
  sandbox/tests/test scenes/_assets/geometry/back_wall.obj
  sandbox/tests/test scenes/_assets/geometry/ceiling.obj
  sandbox/tests/test scenes/_assets/geometry/floor.obj
  sandbox/tests/test scenes/_assets/geometry/left_wall.obj
  sandbox/tests/test scenes/_assets/geometry/light.obj
  sandbox/tests/test scenes/_assets/geometry/right_wall.obj
  sandbox/tests/test scenes/_assets/geometry/short_block.obj
  sandbox/tests/test scenes/_assets/geometry/tall_block.obj
  sandbox/tests/test scenes/analytic lights/03 - rectangle and spheres.appleseed
  sandbox/tests/test scenes/analytic lights/04 - sphere.appleseed
  sandbox/tests/test scenes/analytic lights/05 - disk.appleseed
  sandbox/tests/test scenes/analytic lights/ref/03 - rectangle and spheres.png
  sandbox/tests/test scenes/analytic lights/ref/04 - sphere.png
  sandbox/tests/test scenes/analytic lights/ref/05 - disk.png
  src/appleseed/renderer/kernel/intersection/intersector.cpp
  src/appleseed/renderer/kernel/intersection/intersector.h
  src/appleseed/renderer/kernel/lighting/lightsample.h
  src/appleseed/renderer/kernel/lighting/lightsamplerbase.cpp
  src/appleseed/renderer/kernel/lighting/lighttypes.cpp
  src/appleseed/renderer/kernel/lighting/lighttypes.h
  src/appleseed/renderer/modeling/object/diskobject.cpp
  src/appleseed/renderer/modeling/object/diskobject.h
Labels: PR-Squash

#2631 Move redundant slots into single connect
  src/appleseed.studio/mainwindow/mainwindow.cpp
Labels: PR | Squash

#2625 Allow frame renderers to control rendering
  sandbox/examples/cpp/helloworld/helloworld.cpp
  sandbox/examples/python/helloworld/README.md
  sandbox/examples/python/helloworld/README.pdf
  sandbox/examples/python/helloworld/helloworld.py
  src/appleseed.cli/main.cpp
  src/appleseed.python/bindmasterrenderer.cpp
  src/appleseed.studio/mainwindow/rendering/renderingmanager.cpp
  src/appleseed.studio/mainwindow/rendering/renderingmanager.h
  src/appleseed/renderer/kernel/rendering/generic/genericframerenderer.cpp
  src/appleseed/renderer/kernel/rendering/iframerenderer.h
  src/appleseed/renderer/kernel/rendering/irenderercontroller.h
  src/appleseed/renderer/kernel/rendering/masterrenderer.cpp
  src/appleseed/renderer/kernel/rendering/masterrenderer.h
  src/appleseed/renderer/kernel/rendering/progressive/progressiveframerenderer.cpp
Labels: WIP ⚠
